version: '3'

services:
  dbos:
    image: mysql:5.7
    volumes: 
      - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: arpit
      MYSQL_PASSWORD: arpit20
      MYSQL_DATABASE: mydb

  wpos:
    image: wordpress:5.1.1-php7.3-apache
    depends_on: 
      - dbos
    volumes:
      - wp_storage:/var/www/html
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: arpit
      WORDPRESS_DB_PASSWORD: arpit20
      WORDPRESS_DB_NAME: mydb


volumes:
  mysql_storage:
  wp_storage:
